AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Create aws-codepipeline-dashboard application
Parameters:
  PipelinePattern:
    Description: "The pattern of pipeline names to allow access to describe.  Recommended value: *"
    Type: String
  BucketName:
    Description: "S3 BucketName the Python package. For example: codepipeline-dashboard"
    Type: String
  CodeKey:
    Description: "S3 Key for the Python package. For example: codepipeline-dashboard.zip"
    Type: String
Resources:
  PipelineDashboardEventHandler:
    Type: AWS::Serverless::Function
    Properties:
      Description: Create CloudWatch metrics from CodePipeline events
      Handler: main.pipeline_event_handler
      Runtime: python3.8
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Environment:
        Variables:
          PIPELINE_PATTERN: !Ref PipelinePattern
      Events:
        PipelineEventRule:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.codepipeline
              detail-type:
                - CodePipeline Pipeline Execution State Change
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - CodePipelineReadOnlyPolicy:
            PipelineName: !Ref PipelinePattern
  PipelineDashboardGenerator:
    Type: AWS::Serverless::Function
    Properties:
      Description: Build CloudWatch dashboard from CloudWatch metrics
      Handler: main.dashboard_handler
      Runtime: python3.8
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Timeout: 60
      Events:
        DashboardEventRule:
          Type: Schedule
          Properties:
            Schedule: cron(*/5 * * * ? *)
      Policies:
        - CloudWatchDashboardPolicy: {}
